import { CollectionConfig } from "payload/types";


const Videos: CollectionConfig = {
  slug: 'videos',
  // Most of these are generated by the payload-mux plugin
  fields: []
};

export default Videos;
